spring:
  datasource:
     url: jdbc:mysql://localhost:3306/test1
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver

#mybatis
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.za.*.domain

server:
  port: 8081
servlet:
  context-path: wh

logging:
  file: ./log/whdb_logger.txt
  level:
    com.za.wh_db: debug
  root: info



